### PR TITLE
added command handler

### PR DESCRIPTION
**Pull request by ghost**
i got triggered a lot of times making this

only command that is available is "!ping"

### CODE REVIEW

**Comment by Tenrys** [comment]
discordia.log present, seems to have some conflicts

**Comment by ghost** [comment]
also please setup env. variables:
DISCORD_GROUP_DEVELOPERS (id)
DISCORD_GROUP_ADMINS (id)

**Comment by ghost** [comment]
hold on a minute

**Comment by ghost** [comment]
there we go

**Comment by ghost** [comment]
@Python1320

**Pull request merged**
